-- PitchPoint demo dataset: Brussels-Capital Region
--
-- Populates users, pitches and bookings with a large, realistic set of
-- football pitches spread across all 19 communes of the Brussels-Capital
-- Region, plus owner/player accounts and a spread of bookings.
--
-- All demo accounts share the password: password123
--
-- SAFE TO RE-RUN: wipes existing rows first (children before parents, to
-- respect foreign keys) and resets auto-increment counters, so running
-- this twice always leaves the same clean dataset rather than piling up
-- duplicates.
--
-- Usage:
--   mysql -u <user> -p pitchpoint < seed_brussels.sql

START TRANSACTION;

DELETE FROM bookings;
DELETE FROM pitches;
DELETE FROM users;
ALTER TABLE bookings AUTO_INCREMENT = 1;
ALTER TABLE pitches AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;

-- ============================================================
-- Users: 6 owners (each managing a group of communes) + 5 players
-- ============================================================
INSERT INTO users (name, email, passwordHash, role, createdAt, updatedAt) VALUES
('Bruxelles Sports asbl', 'owner.brussels@pitchpoint-demo.be', '$2b$10$BPDzKQAebobiXLTvCCQtpOakocPM6TSc.MX7FUxgA2znncRydBPgG', 'owner', NOW(), NOW()),
('Anderlecht Sports asbl', 'owner.anderlecht@pitchpoint-demo.be', '$2b$10$BPDzKQAebobiXLTvCCQtpOakocPM6TSc.MX7FUxgA2znncRydBPgG', 'owner', NOW(), NOW()),
('South Brussels Pitches', 'owner.south@pitchpoint-demo.be', '$2b$10$BPDzKQAebobiXLTvCCQtpOakocPM6TSc.MX7FUxgA2znncRydBPgG', 'owner', NOW(), NOW()),
('Schaerbeek-Evere Sport', 'owner.northeast@pitchpoint-demo.be', '$2b$10$BPDzKQAebobiXLTvCCQtpOakocPM6TSc.MX7FUxgA2znncRydBPgG', 'owner', NOW(), NOW()),
('Woluwe Sports Group', 'owner.woluwe@pitchpoint-demo.be', '$2b$10$BPDzKQAebobiXLTvCCQtpOakocPM6TSc.MX7FUxgA2znncRydBPgG', 'owner', NOW(), NOW()),
('Ixelles-Etterbeek Facilities', 'owner.ixelles@pitchpoint-demo.be', '$2b$10$BPDzKQAebobiXLTvCCQtpOakocPM6TSc.MX7FUxgA2znncRydBPgG', 'owner', NOW(), NOW()),
('Lucas Dubois', 'lucas.dubois@pitchpoint-demo.be', '$2b$10$BPDzKQAebobiXLTvCCQtpOakocPM6TSc.MX7FUxgA2znncRydBPgG', 'player', NOW(), NOW()),
('Amina El Amrani', 'amina.elamrani@pitchpoint-demo.be', '$2b$10$BPDzKQAebobiXLTvCCQtpOakocPM6TSc.MX7FUxgA2znncRydBPgG', 'player', NOW(), NOW()),
('Thomas Peeters', 'thomas.peeters@pitchpoint-demo.be', '$2b$10$BPDzKQAebobiXLTvCCQtpOakocPM6TSc.MX7FUxgA2znncRydBPgG', 'player', NOW(), NOW()),
('Fatima Zahra', 'fatima.zahra@pitchpoint-demo.be', '$2b$10$BPDzKQAebobiXLTvCCQtpOakocPM6TSc.MX7FUxgA2znncRydBPgG', 'player', NOW(), NOW()),
('Nicolas Janssens', 'nicolas.janssens@pitchpoint-demo.be', '$2b$10$BPDzKQAebobiXLTvCCQtpOakocPM6TSc.MX7FUxgA2znncRydBPgG', 'player', NOW(), NOW());

-- Owner user ids are 1-6 (insertion order above), player ids are 7-11.

-- ============================================================
-- Pitches: 38 pitches, 2 per commune, across all 19 communes
-- ============================================================
INSERT INTO pitches (name, address, lat, lng, surfaceType, size, pricePerHour, photos, openTime, closeTime, ownerId, createdAt, updatedAt) VALUES
('Complexe Sportif Bruxelles-Ville', 'Rue du Stade 23, 1000 Bruxelles-Ville', 50.852300, 4.349900, 'grass', '11v11', 72.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Zambian_football_play_aerial_view.jpg/960px-Zambian_football_play_aerial_view.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/6/6d/Bolton_Wanderers_Eddie_Davies_Football_Academy%2C_Artificial_training_pitch_-_geograph.org.uk_-_1221227.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled"]', '07:00:00', '22:00:00', 1, NOW(), NOW()),
('Terrain Bruxelles-Ville II', 'Rue du Stade 36, 1000 Bruxelles-Ville', 50.847800, 4.353900, 'indoor', '7v7', 56.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Johnstone_Burgh_Football_Club_-_geograph.org.uk_-_5148398.jpg/960px-Johnstone_Burgh_Football_Club_-_geograph.org.uk_-_5148398.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/7/7d/Pitch_at_Colney_Training_Centre%2C_Norwich_City_Football_Club_-_geograph.org.uk_-_1498175.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled"]', '08:00:00', '23:00:00', 1, NOW(), NOW()),
('Five Football Anderlecht', 'Rue du Stade 49, 1070 Anderlecht', 50.838700, 4.292000, 'artificial_turf', '7v7', 45.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/New_Meadow%2C_home_of_Shrewsbury_Town_Football_Club_-_geograph.org.uk_-_7472442.jpg/960px-New_Meadow%2C_home_of_Shrewsbury_Town_Football_Club_-_geograph.org.uk_-_7472442.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Iran_mens_national_football_team_training_3.jpg/960px-Iran_mens_national_football_team_training_3.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '06:00:00', '21:00:00', 2, NOW(), NOW()),
('Stade Communal de Anderlecht II', 'Rue du Stade 62, 1070 Anderlecht', 50.834200, 4.296000, 'grass', '5v5', 32.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Aerial_view_of_the_Chatham_Town_FC_football_pitch.jpg/960px-Aerial_view_of_the_Chatham_Town_FC_football_pitch.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Iran_mens_national_football_team_training_2.jpg/960px-Iran_mens_national_football_team_training_2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '09:00:00', '22:00:00', 2, NOW(), NOW()),
('Complexe Sportif Auderghem', 'Rue du Stade 75, 1160 Auderghem', 50.816400, 4.435200, 'indoor', '5v5', 39.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/DFC_5329_Evening_kickabout_in_Klet_Kaeo_-_teammates_line_up_as_a_player_strikes_the_ball_on_the_artificial_turf.jpg/960px-DFC_5329_Evening_kickabout_in_Klet_Kaeo_-_teammates_line_up_as_a_player_strikes_the_ball_on_the_artificial_turf.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Association_football_goal_in_training_football_field_cropped.jpg/960px-Association_football_goal_in_training_football_field_cropped.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '07:00:00', '23:00:00', 5, NOW(), NOW()),
('Terrain Auderghem II', 'Rue du Stade 88, 1160 Auderghem', 50.811900, 4.439200, 'artificial_turf', '11v11', 77.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/DZ6_2354_Empty_bleachers_and_a_covered_grandstand_overlook_a_quiet_artificial-turf_sports_field_at_dusk.jpg/960px-DZ6_2354_Empty_bleachers_and_a_covered_grandstand_overlook_a_quiet_artificial-turf_sports_field_at_dusk.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Jokolela_training_pitch.jpg/960px-Jokolela_training_pitch.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '10:00:00', '20:00:00', 5, NOW(), NOW()),
('Five Football Berchem-Sainte-Agathe', 'Rue du Stade 101, 1082 Berchem-Sainte-Agathe', 50.865200, 4.285200, 'grass', '11v11', 84.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/IndoorSoccerInMexico.jpg/960px-IndoorSoccerInMexico.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Saturday_afternoon_football_training_-_geograph.org.uk_-_4413324.jpg/960px-Saturday_afternoon_football_training_-_geograph.org.uk_-_4413324.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '08:00:00', '22:00:00', 2, NOW(), NOW()),
('Stade Communal de Berchem-Sainte-Agathe II', 'Rue du Stade 114, 1082 Berchem-Sainte-Agathe', 50.860700, 4.289200, 'indoor', '7v7', 44.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Indoor_Soccer_Game_in_Mexico.JPG/960px-Indoor_Soccer_Game_in_Mexico.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Bangor_City_Football_Club_training_pitch_-_geograph.org.uk_-_5319039.jpg/960px-Bangor_City_Football_Club_training_pitch_-_geograph.org.uk_-_5319039.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '06:00:00', '23:00:00', 2, NOW(), NOW()),
('Complexe Sportif Etterbeek', 'Rue du Stade 127, 1040 Etterbeek', 50.838700, 4.388200, 'artificial_turf', '7v7', 51.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Indoor_soccer_singapore_z.JPG/960px-Indoor_soccer_singapore_z.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Young_footballers_in_training_-_geograph.org.uk_-_6861188.jpg/960px-Young_footballers_in_training_-_geograph.org.uk_-_6861188.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '07:00:00', '22:00:00', 6, NOW(), NOW()),
('Terrain Etterbeek II', 'Rue du Stade 140, 1040 Etterbeek', 50.834200, 4.392200, 'grass', '5v5', 38.50, '["https://upload.wikimedia.org/wikipedia/commons/f/f1/Small_football_pitch%2C_behind_Horsforth_Woodside_Bowling_Club%2C_Low_Lane_-_geograph.org.uk_-_194665.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled","https://upload.wikimedia.org/wikipedia/commons/9/9a/Unst_football_pitch%2C_Baltasound_-_geograph.org.uk_-_1341534.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled"]', '08:00:00', '23:00:00', 6, NOW(), NOW()),
('Five Football Evere', 'Rue du Stade 153, 1140 Evere', 50.871800, 4.400500, 'indoor', '5v5', 33.50, '["https://upload.wikimedia.org/wikipedia/commons/f/fd/Small_Dole_Sports_Ground_-_geograph.org.uk_-_757054.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled","https://upload.wikimedia.org/wikipedia/commons/3/38/Unst_football_pitch%2C_Baltasound_-_geograph.org.uk_-_1341544.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled"]', '06:00:00', '21:00:00', 4, NOW(), NOW()),
('Stade Communal de Evere II', 'Rue du Stade 166, 1140 Evere', 50.867300, 4.404500, 'artificial_turf', '11v11', 89.50, '["https://upload.wikimedia.org/wikipedia/commons/3/37/Pvsk_small_football_pitch.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled","https://upload.wikimedia.org/wikipedia/commons/8/8c/Unst_football_pitch%2C_Baltasound_-_geograph.org.uk_-_1341550.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled"]', '09:00:00', '22:00:00', 4, NOW(), NOW()),
('Complexe Sportif Forest', 'Rue du Stade 179, 1190 Forest', 50.811300, 4.319000, 'grass', '11v11', 66.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/DMTK_Sports_fields%2C_small_football_field%2C_2019_Dunaharaszti.jpg/960px-DMTK_Sports_fields%2C_small_football_field%2C_2019_Dunaharaszti.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Dolgellau_Athletic_Amateur_Football_Club_Pitch-geograph-4452529-by-Jeff-Buck.jpg/960px-Dolgellau_Athletic_Amateur_Football_Club_Pitch-geograph-4452529-by-Jeff-Buck.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '07:00:00', '23:00:00', 3, NOW(), NOW()),
('Terrain Forest II', 'Rue du Stade 12, 1190 Forest', 50.806800, 4.323000, 'indoor', '7v7', 50.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Small_hut_by_the_football_field_and_canal_in_Mytholmroyd.jpg/960px-Small_hut_by_the_football_field_and_canal_in_Mytholmroyd.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Indoor_pitch%2C_Toryglen_Regional_Football_Centre_%28geograph_5699176%29.jpg/960px-Indoor_pitch%2C_Toryglen_Regional_Football_Centre_%28geograph_5699176%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '10:00:00', '20:00:00', 3, NOW(), NOW()),
('Five Football Ganshoren', 'Rue du Stade 25, 1083 Ganshoren', 50.869200, 4.310300, 'artificial_turf', '7v7', 57.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/A_small_football_field_-_geograph.org.uk_-_5845038.jpg/960px-A_small_football_field_-_geograph.org.uk_-_5845038.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Indoor_pitch%2C_Toryglen_Regional_Football_Centre_%28geograph_5699172%29.jpg/960px-Indoor_pitch%2C_Toryglen_Regional_Football_Centre_%28geograph_5699172%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '08:00:00', '22:00:00', 2, NOW(), NOW()),
('Stade Communal de Ganshoren II', 'Rue du Stade 38, 1083 Ganshoren', 50.864700, 4.314300, 'grass', '5v5', 32.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Small_football_pitch_-_geograph.org.uk_-_6872800.jpg/960px-Small_football_pitch_-_geograph.org.uk_-_6872800.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/3/37/Artificial_%22five_a_side%22_football_pitch_-_geograph.org.uk_-_1915895.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled"]', '06:00:00', '23:00:00', 2, NOW(), NOW()),
('Complexe Sportif Ixelles', 'Rue du Stade 51, 1050 Ixelles', 50.835300, 4.364900, 'indoor', '5v5', 39.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Football_pitch_squeezed_into_a_small_space_-_geograph.org.uk_-_8325606.jpg/960px-Football_pitch_squeezed_into_a_small_space_-_geograph.org.uk_-_8325606.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/7/7a/Five_a_Side_Football_Pitch_-_Wellington_Place_-_geograph.org.uk_-_1986946.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled"]', '07:00:00', '22:00:00', 6, NOW(), NOW()),
('Terrain Ixelles II', 'Rue du Stade 64, 1050 Ixelles', 50.830800, 4.368900, 'artificial_turf', '11v11', 71.50, '["https://upload.wikimedia.org/wikipedia/commons/2/25/Old_Patesians_5-aside_football-training_pitch_-_geograph.org.uk_-_1175457.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled","https://upload.wikimedia.org/wikipedia/commons/1/1c/Five-a-Side_Football_Pitch_at_MediaCityUK_-_geograph.org.uk_-_4855419.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled"]', '08:00:00', '23:00:00', 6, NOW(), NOW()),
('Five Football Jette', 'Rue du Stade 77, 1090 Jette', 50.880500, 4.323700, 'grass', '11v11', 78.50, '["https://upload.wikimedia.org/wikipedia/commons/6/6d/Bolton_Wanderers_Eddie_Davies_Football_Academy%2C_Artificial_training_pitch_-_geograph.org.uk_-_1221227.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled","https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Five-a-side_pitch_at_Plantation_Park_Football_Ground_-_geograph.org.uk_-_5832811.jpg/960px-Five-a-side_pitch_at_Plantation_Park_Football_Ground_-_geograph.org.uk_-_5832811.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '06:00:00', '21:00:00', 2, NOW(), NOW()),
('Stade Communal de Jette II', 'Rue du Stade 90, 1090 Jette', 50.876000, 4.327700, 'indoor', '7v7', 56.50, '["https://upload.wikimedia.org/wikipedia/commons/7/7d/Pitch_at_Colney_Training_Centre%2C_Norwich_City_Football_Club_-_geograph.org.uk_-_1498175.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled","https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Zambian_football_play_aerial_view.jpg/960px-Zambian_football_play_aerial_view.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '09:00:00', '22:00:00', 2, NOW(), NOW()),
('Complexe Sportif Koekelberg', 'Rue du Stade 103, 1081 Koekelberg', 50.861800, 4.326900, 'artificial_turf', '7v7', 45.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Iran_mens_national_football_team_training_3.jpg/960px-Iran_mens_national_football_team_training_3.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Johnstone_Burgh_Football_Club_-_geograph.org.uk_-_5148398.jpg/960px-Johnstone_Burgh_Football_Club_-_geograph.org.uk_-_5148398.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '07:00:00', '23:00:00', 1, NOW(), NOW()),
('Terrain Koekelberg II', 'Rue du Stade 116, 1081 Koekelberg', 50.857300, 4.330900, 'grass', '5v5', 38.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Iran_mens_national_football_team_training_2.jpg/960px-Iran_mens_national_football_team_training_2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/New_Meadow%2C_home_of_Shrewsbury_Town_Football_Club_-_geograph.org.uk_-_7472442.jpg/960px-New_Meadow%2C_home_of_Shrewsbury_Town_Football_Club_-_geograph.org.uk_-_7472442.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '10:00:00', '20:00:00', 1, NOW(), NOW()),
('Five Football Molenbeek-Saint-Jean', 'Rue du Stade 129, 1080 Molenbeek-Saint-Jean', 50.857400, 4.318600, 'indoor', '5v5', 33.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Association_football_goal_in_training_football_field_cropped.jpg/960px-Association_football_goal_in_training_football_field_cropped.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Aerial_view_of_the_Chatham_Town_FC_football_pitch.jpg/960px-Aerial_view_of_the_Chatham_Town_FC_football_pitch.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '08:00:00', '22:00:00', 1, NOW(), NOW()),
('Stade Communal de Molenbeek-Saint-Jean II', 'Rue du Stade 142, 1080 Molenbeek-Saint-Jean', 50.852900, 4.322600, 'artificial_turf', '11v11', 83.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Jokolela_training_pitch.jpg/960px-Jokolela_training_pitch.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/DFC_5329_Evening_kickabout_in_Klet_Kaeo_-_teammates_line_up_as_a_player_strikes_the_ball_on_the_artificial_turf.jpg/960px-DFC_5329_Evening_kickabout_in_Klet_Kaeo_-_teammates_line_up_as_a_player_strikes_the_ball_on_the_artificial_turf.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '06:00:00', '23:00:00', 1, NOW(), NOW()),
('Complexe Sportif Saint-Gilles', 'Rue du Stade 155, 1060 Saint-Gilles', 50.828300, 4.344100, 'grass', '11v11', 90.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Saturday_afternoon_football_training_-_geograph.org.uk_-_4413324.jpg/960px-Saturday_afternoon_football_training_-_geograph.org.uk_-_4413324.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/DZ6_2354_Empty_bleachers_and_a_covered_grandstand_overlook_a_quiet_artificial-turf_sports_field_at_dusk.jpg/960px-DZ6_2354_Empty_bleachers_and_a_covered_grandstand_overlook_a_quiet_artificial-turf_sports_field_at_dusk.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '07:00:00', '22:00:00', 3, NOW(), NOW()),
('Terrain Saint-Gilles II', 'Rue du Stade 168, 1060 Saint-Gilles', 50.823800, 4.348100, 'indoor', '7v7', 44.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Bangor_City_Football_Club_training_pitch_-_geograph.org.uk_-_5319039.jpg/960px-Bangor_City_Football_Club_training_pitch_-_geograph.org.uk_-_5319039.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/IndoorSoccerInMexico.jpg/960px-IndoorSoccerInMexico.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '08:00:00', '23:00:00', 3, NOW(), NOW()),
('Five Football Saint-Josse-ten-Noode', 'Rue du Stade 181, 1210 Saint-Josse-ten-Noode', 50.852800, 4.367400, 'artificial_turf', '7v7', 51.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Young_footballers_in_training_-_geograph.org.uk_-_6861188.jpg/960px-Young_footballers_in_training_-_geograph.org.uk_-_6861188.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Indoor_Soccer_Game_in_Mexico.JPG/960px-Indoor_Soccer_Game_in_Mexico.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '06:00:00', '21:00:00', 4, NOW(), NOW()),
('Stade Communal de Saint-Josse-ten-Noode II', 'Rue du Stade 14, 1210 Saint-Josse-ten-Noode', 50.848300, 4.371400, 'grass', '5v5', 32.50, '["https://upload.wikimedia.org/wikipedia/commons/9/9a/Unst_football_pitch%2C_Baltasound_-_geograph.org.uk_-_1341534.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled","https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Indoor_soccer_singapore_z.JPG/960px-Indoor_soccer_singapore_z.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '09:00:00', '22:00:00', 4, NOW(), NOW()),
('Complexe Sportif Schaerbeek', 'Rue du Stade 27, 1030 Schaerbeek', 50.869600, 4.372000, 'indoor', '5v5', 39.50, '["https://upload.wikimedia.org/wikipedia/commons/3/38/Unst_football_pitch%2C_Baltasound_-_geograph.org.uk_-_1341544.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled","https://upload.wikimedia.org/wikipedia/commons/f/f1/Small_football_pitch%2C_behind_Horsforth_Woodside_Bowling_Club%2C_Low_Lane_-_geograph.org.uk_-_194665.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled"]', '07:00:00', '23:00:00', 4, NOW(), NOW()),
('Terrain Schaerbeek II', 'Rue du Stade 40, 1030 Schaerbeek', 50.865100, 4.376000, 'artificial_turf', '11v11', 65.50, '["https://upload.wikimedia.org/wikipedia/commons/8/8c/Unst_football_pitch%2C_Baltasound_-_geograph.org.uk_-_1341550.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled","https://upload.wikimedia.org/wikipedia/commons/f/fd/Small_Dole_Sports_Ground_-_geograph.org.uk_-_757054.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled"]', '10:00:00', '20:00:00', 4, NOW(), NOW()),
('Five Football Uccle', 'Rue du Stade 53, 1180 Uccle', 50.803400, 4.334000, 'grass', '11v11', 72.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Dolgellau_Athletic_Amateur_Football_Club_Pitch-geograph-4452529-by-Jeff-Buck.jpg/960px-Dolgellau_Athletic_Amateur_Football_Club_Pitch-geograph-4452529-by-Jeff-Buck.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/3/37/Pvsk_small_football_pitch.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled"]', '08:00:00', '22:00:00', 3, NOW(), NOW()),
('Stade Communal de Uccle II', 'Rue du Stade 66, 1180 Uccle', 50.798900, 4.338000, 'indoor', '7v7', 50.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Indoor_pitch%2C_Toryglen_Regional_Football_Centre_%28geograph_5699176%29.jpg/960px-Indoor_pitch%2C_Toryglen_Regional_Football_Centre_%28geograph_5699176%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/DMTK_Sports_fields%2C_small_football_field%2C_2019_Dunaharaszti.jpg/960px-DMTK_Sports_fields%2C_small_football_field%2C_2019_Dunaharaszti.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '06:00:00', '23:00:00', 3, NOW(), NOW()),
('Complexe Sportif Watermael-Boitsfort', 'Rue du Stade 79, 1170 Watermael-Boitsfort', 50.804000, 4.416700, 'artificial_turf', '7v7', 57.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Indoor_pitch%2C_Toryglen_Regional_Football_Centre_%28geograph_5699172%29.jpg/960px-Indoor_pitch%2C_Toryglen_Regional_Football_Centre_%28geograph_5699172%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Small_hut_by_the_football_field_and_canal_in_Mytholmroyd.jpg/960px-Small_hut_by_the_football_field_and_canal_in_Mytholmroyd.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '07:00:00', '22:00:00', 5, NOW(), NOW()),
('Terrain Watermael-Boitsfort II', 'Rue du Stade 92, 1170 Watermael-Boitsfort', 50.799500, 4.420700, 'grass', '5v5', 38.50, '["https://upload.wikimedia.org/wikipedia/commons/3/37/Artificial_%22five_a_side%22_football_pitch_-_geograph.org.uk_-_1915895.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled","https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/A_small_football_field_-_geograph.org.uk_-_5845038.jpg/960px-A_small_football_field_-_geograph.org.uk_-_5845038.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '08:00:00', '23:00:00', 5, NOW(), NOW()),
('Five Football Woluwe-Saint-Lambert', 'Rue du Stade 105, 1200 Woluwe-Saint-Lambert', 50.848700, 4.430900, 'indoor', '5v5', 33.50, '["https://upload.wikimedia.org/wikipedia/commons/7/7a/Five_a_Side_Football_Pitch_-_Wellington_Place_-_geograph.org.uk_-_1986946.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled","https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Small_football_pitch_-_geograph.org.uk_-_6872800.jpg/960px-Small_football_pitch_-_geograph.org.uk_-_6872800.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '06:00:00', '21:00:00', 5, NOW(), NOW()),
('Stade Communal de Woluwe-Saint-Lambert II', 'Rue du Stade 118, 1200 Woluwe-Saint-Lambert', 50.844200, 4.434900, 'artificial_turf', '11v11', 77.50, '["https://upload.wikimedia.org/wikipedia/commons/1/1c/Five-a-Side_Football_Pitch_at_MediaCityUK_-_geograph.org.uk_-_4855419.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled","https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Football_pitch_squeezed_into_a_small_space_-_geograph.org.uk_-_8325606.jpg/960px-Football_pitch_squeezed_into_a_small_space_-_geograph.org.uk_-_8325606.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail"]', '09:00:00', '22:00:00', 5, NOW(), NOW()),
('Complexe Sportif Woluwe-Saint-Pierre', 'Rue du Stade 131, 1150 Woluwe-Saint-Pierre', 50.831800, 4.452900, 'grass', '11v11', 84.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Five-a-side_pitch_at_Plantation_Park_Football_Ground_-_geograph.org.uk_-_5832811.jpg/960px-Five-a-side_pitch_at_Plantation_Park_Football_Ground_-_geograph.org.uk_-_5832811.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/2/25/Old_Patesians_5-aside_football-training_pitch_-_geograph.org.uk_-_1175457.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled"]', '07:00:00', '23:00:00', 5, NOW(), NOW()),
('Terrain Woluwe-Saint-Pierre II', 'Rue du Stade 144, 1150 Woluwe-Saint-Pierre', 50.827300, 4.456900, 'indoor', '7v7', 56.50, '["https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Zambian_football_play_aerial_view.jpg/960px-Zambian_football_play_aerial_view.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","https://upload.wikimedia.org/wikipedia/commons/6/6d/Bolton_Wanderers_Eddie_Davies_Football_Academy%2C_Artificial_training_pitch_-_geograph.org.uk_-_1221227.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled"]', '10:00:00', '20:00:00', 5, NOW(), NOW());

-- Pitch ids are 1-38 in insertion order above.

-- ============================================================
-- Bookings: a spread of confirmed/cancelled bookings across players,
-- pitches and dates (past, present and future relative to seed time).
-- ============================================================
INSERT INTO bookings (pitchId, userId, date, startTime, endTime, status, createdAt, updatedAt) VALUES
(1, 7, '2026-07-18', '07:00', '08:00', 'confirmed', NOW(), NOW()),
(3, 8, '2026-07-25', '07:00', '09:00', 'confirmed', NOW(), NOW()),
(5, 9, '2026-08-05', '09:00', '10:00', 'confirmed', NOW(), NOW()),
(7, 10, '2026-08-14', '11:00', '13:00', 'cancelled', NOW(), NOW()),
(9, 11, '2026-08-21', '11:00', '12:00', 'confirmed', NOW(), NOW()),
(11, 7, '2026-08-28', '11:00', '13:00', 'confirmed', NOW(), NOW()),
(13, 8, '2026-09-04', '13:00', '14:00', 'confirmed', NOW(), NOW()),
(15, 9, '2026-09-12', '15:00', '17:00', 'cancelled', NOW(), NOW()),
(17, 10, '2026-09-20', '15:00', '16:00', 'confirmed', NOW(), NOW()),
(19, 11, '2026-10-02', '15:00', '17:00', 'confirmed', NOW(), NOW()),
(21, 7, '2026-07-18', '17:00', '18:00', 'confirmed', NOW(), NOW()),
(23, 8, '2026-07-25', '19:00', '21:00', 'cancelled', NOW(), NOW()),
(25, 9, '2026-08-05', '19:00', '20:00', 'confirmed', NOW(), NOW()),
(27, 10, '2026-08-14', '06:00', '08:00', 'confirmed', NOW(), NOW()),
(29, 11, '2026-08-21', '21:00', '22:00', 'confirmed', NOW(), NOW()),
(31, 7, '2026-08-28', '11:00', '13:00', 'cancelled', NOW(), NOW()),
(33, 8, '2026-09-04', '09:00', '10:00', 'confirmed', NOW(), NOW()),
(35, 9, '2026-09-12', '10:00', '12:00', 'confirmed', NOW(), NOW()),
(37, 10, '2026-09-20', '10:00', '11:00', 'confirmed', NOW(), NOW());

COMMIT;

-- Quick sanity check after running:
--   SELECT COUNT(*) FROM users;    -- 11
--   SELECT COUNT(*) FROM pitches;  -- 38
--   SELECT COUNT(*) FROM bookings; -- 19
